# Generated by Django 3.1.8 on 2022-12-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booka',
            new_name='Book',
        ),
    ]
